---
# Set builder-type specific variables
# Note: packer_builder_type is automatically made available as an ansible
# variable by packer.
- name: Assign variables based on Packer builder type.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ packer_builder_type }}.yml"
    - "default_builder.yml"

- name: Install devtools.
  import_role:
    name: general-packages
  vars:
    needed_packages:
      - build-essential
      - m4
      - cmake

- name: Prepare to add thredds-test-environment native libraries to run-time linker
  copy:
    dest: "/etc/ld.so.conf.d/tte.conf"
    content: "{{ install_dir }}/lib"

- include_tasks: zlib.yml
  tags: [ zlib ]

- include_tasks: hdf5.yml
  tags: [ hdf5 ]

- include_tasks: netcdf-c.yml
  tags: [ netcdf-c ]
